### ISSUE TITLE
Change the contract name from "Shankai" to "FIFA WC2018"

### ISSUE THREAD

**Issue by zhangzhongnan928** [alpha-wallet/contracts#10]
Desired look:

![40096672-82d69150-5904-11e8-9e63-a9ef44c409e5](https://user-images.githubusercontent.com/33795543/40096803-25471360-5905-11e8-8ebe-fbb0293bab30.gif)

**Comment by zhangzhongnan928** [comment]
Since it is a bad idea to use different names in XML for main net and test testnet.
Please follow below instruction to do the changes,
![img_3451](https://user-images.githubusercontent.com/33795543/40096213-7bbb74d2-5902-11e8-99ce-82f79373f00a.PNG)

**Comment by James-Sangalli** [comment]
Done
