### ISSUE TITLE
Multi-contract (in the same network) support for XML?

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/contracts#51]
Is multiple address elements with the same network attribute value valid (network="1" below) or should this be in 2 separate XMLs (with mostly duplicated content)? I noticed the repo server serves the file correctly for all 3 addresses.

```
<contract id="holding_contract" type="holding">
    <address network="1">0xA66A3F08068174e8F005112A8b2c7A507a822335</address>
    <address network="3">0xd8e5f58de3933e1e35f9c65eb72cb188674624f3</address>
    <address network="1">0x830E1650a87a754e37ca7ED76b700395A7C61614</address>
    ...
</contract>
```

**Comment by colourful-land** [comment]
Not in the first year. it has security consequences which I prefer to deal with later.
