### ISSUE TITLE
CountryB seems to be encoded wrongly

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/contracts#58]
For BEV token in 0x0d59.

 Or maybe the XML doesn't have the value. Just in case it's a bug.

<img width="474" alt="screen shot 2018-09-27 at 5 51 03 pm" src="https://user-images.githubusercontent.com/56189/46138266-0a57e380-c27e-11e8-8b5c-5a9c2a06c8d2.png">

**Comment by James-Sangalli** [comment]
Yep, I made a mistake during the encoding. Nothing wrong with XML.
